### ISSUE TITLE
AttributeError à la reception d'une trame

### ISSUE THREAD

**Issue by ludoplt** [GendarmerieNationale/ReceptionInfoDrone#1]
Bonjour, 

A la reception d'une trame avec le bon VID, d'une taille supérieur à 70 octets, on tombe systématiquement en AttributeError..

Avez vous constaté cette erreur ? 

La reception et le tri des trames s'effectue bien, mais une fois que json.py tombe en AttributeError, le script json est stoppé et sniff.py ne fait plus qu'ajouter les nouvelles trames dans la queue

**Comment by PercyMgn** [comment]
Bonjour,

Désolé pour la réponse tardive. Une nouvelle version sera publié très prochainement (cette semaine ou semaine prochaine) qui prendra en compte les VendorSpecific multiples. Actuellement, cette version fonctionne quand la trame se compose d'un VS.

Il faudra donc essayer avec la nouvelle version pour voir si le problème persiste.

Cordialement,

**Comment by ludoplt** [comment]
Bonjour, 
Merci pour votre retour, est il possible de savoir quel VS utiliser pour que la version actuelle fonctionne afin d'avancer dans nos développements en attendant la nouvelle version ?

En vous remerciant !

**Comment by PercyMgn** [comment]
Nouvelle version publiée. Dites-moi si cela fonctionne.
Cordialement,

**Comment by ludoplt** [comment]
Ça à l'air de fonctionner ! Merci. 
Par contre le JSON est enregistré quelque-part ou il est juste affiché ?
Si oui il est enregistré à quel endroit ?

**Comment by PercyMgn** [comment]
Ce script a pour but d'afficher uniquement la trame dans un JSON afin de vérifier la conformité de la trame venant d'un drone ou d'un dispositif de signalement électronique.

**Comment by PercyMgn** [comment]
Merci de fermer le "issue".

**Comment by ludoplt** [comment]
Merci !
