### ISSUE TITLE
Incompatibilité de licence entre le programme et la bibliothèque Scapy

### ISSUE THREAD

**Issue by Saxodwarf** [GendarmerieNationale/ReceptionInfoDrone#3]
Bonjour,

Vous distribuez actuellement votre code sous double licence CeCILL v2.1 et GPLv2.
Cependant, vous distribuez et dépendez de la bibliothèque Scapy, qui est distribuée sous GPLv2.

Il n'est donc pas possible de publier votre code sous la licence CeCILL (voir https://cecill.info/placer.fr.html#emprunt).
Vous devriez revoir votre licence, ou supprimer votre dépendance à Scapy.

Bien cordialement.

**Comment by guimard** [comment]
Fait, merci
