### ISSUE TITLE
AWUS1900wifi a/b/g/n bi-bande (2Ghz et 5Ghz)

### ISSUE THREAD

**Issue by guillaumebosse** [GendarmerieNationale/ReceptionInfoDrone#5]
bonjour,
j ai reussi a faire fonctionner le tout…
mais cela ne fonctionne pas avec toute les clés wifi (bien qu’elles acceptent le mode monitoring)
celle ci fonctionne sans probleme * TP-Link TL-WN722N (version 1) mais celle la:
AWUS1900wifi a/b/g/n bi-bande (2Ghz et 5Ghz)
me renvoie un message d erreur apres un control C

Lancement du script.
Lancement du mode monitor.
Mode monitor de l’interface wlan0

^CProcess json:
Arret du script.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File “/usr/lib/python3.8/multiprocessing/popen_fork.py”, line 27, in poll
pid, sts = os.waitpid(self.pid, flag)
File “main.py”, line 74, in signal_handler
monitorStop()
File “main.py”, line 59, in monitorStop
airmon_ng(“stop”, interface_wifi).exit_code == 0
File “/home/bigboss/Documents/ReceptionInfoDrone-master/lib/sh/sh.py”, line 1427, in call
return RunningCommand(cmd, call_args, stdin, stdout, stderr)
File “/home/bigboss/Documents/ReceptionInfoDrone-master/lib/sh/sh.py”, line 774, in init
self.wait()
File “/home/bigboss/Documents/ReceptionInfoDrone-master/lib/sh/sh.py”, line 792, in wait
self.handle_command_exit_code(exit_code)
File “/home/bigboss/Documents/ReceptionInfoDrone-master/lib/sh/sh.py”, line 815, in handle_command_exit_code
raise exc
lib.sh.sh.ErrorReturnCode_1:
RAN: /usr/sbin/airmon-ng stop wlan0
STDOUT
PHY Interface Driver Chipset
phy0 wlan0 rtl88XXau Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac
You already have a wlan0 device but it is NOT in station mode.
Whatever you did, don’t do it again.
Please run “iw wlan0 del” before attempting to continue

des idees ??

**Comment by PercyMgn** [comment]
Bonjour,

Si votre interface wifi se nomme bien "wlan0", merci d'effectuer la commande suivante :
- sudo airmon-ng start wlan0

Puis merci d'effectuer un iwconfig et de m'envoyer le résultat.

Le problème vient probablement du nom de l'interface. 
Certaines interfaces rajoutent à la fin de leur nom un "mon" quand elles passent en mode monitor.

**Comment by PercyMgn** [comment]
En tout cas, le problème est lié à la mise en place du mode monitor et L’arrêt avec vos chipsets wifi et non lié au code proposé.

**Comment by guillaumebosse** [comment]
bonjour,
en effet cela vient des différentes cartes wifi 
j ai trouvé ca comme explication...

You have to set the monitor mode manually on the AWUS036ACH & AWUS1900

## Set interface down
sudo ip link set wlan0 down
 
## Set monitor mode
sudo iwconfig wlan0 mode monitor
 
## Set interface up
sudo ip link set wlan0 up
