### ISSUE TITLE
Fonctionnement avec Raspberry et Kali

### ISSUE THREAD

**Issue by sergerobert** [GendarmerieNationale/ReceptionInfoDrone#6]
Bonjour

Il est possible d'installer Kali d'offensive Security sur un Raspberry 3 model B v 2 (2015), cela permet d'utiliser le chipset WLAN de Broadcom natif en mode "Monitor",  airmon-ng est inclus dans la distribution. Cela évite d'avoir une interface WLAN externe.

image utilisée :
https://images.kali.org/arm-images/kali-linux-2020.3b-rpi3-nexmon-64.img.xz

Pour les tests :
#Passage en super utilisateur  (root)
sudo su

Vérification airmon-ng
airmon-ng check

Arrêt des processus qui utilise l'interface WLAN
airmon-ng check kill

Création de l'interface wlan0 en mode moniteur
airmon-ng wlan0

Pour vérifier 
iwconfig

Pour tester le programme Python :
Kali dans cette version embarque Python 3.8.4 

Le script fonctionne dès que le signalement électronique (celui INOSED GPS pour le drone testé) commence à émettre.
La trame JSON du Drone ne permet pas de voir clairement l'identification décodée au sens de l'arrêté 27 décembre 2019 me semble-t-il ...
https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039685188/

Ma question, est possible d'avoir un script qui décode la trame selon champ de l'arrêté en claire ?

**Comment by PercyMgn** [comment]
Bonjour,
Tout d'abord, désolé pour la réponse tardive.

Afin d'afficher la trame dans son ensemble, vous pouvez rajouter des print() à différents endroits comme par exemple dans le fichier lib/json.py, après
<code class="lang-python">while True:</code>
<code class="lang-python">trame = queue_beacon_sie.get()</code>
Rajouter:
<code class="lang-python"> print("Trame brut : ", trame)</code>

Si j'ai répondu à votre question, merci de me l'indiquer.

Bonne journée,

**Comment by sergerobert** [comment]
Bonjour

Je vous remercie pour votre aide, la modification indiquée fonctionne bien.

J'en profite rajouter une adaptation de la configuration initialement indiquée (Raspberry + Kali) pour ne pas perdre l'interface réseau Ethernet (cuivre) lors du passage de l'interface wlan0 en mode moniteur.

Commencer : 
_Modification du fichier /etc/NeworkManager/NetworkManager.conf_

Avec le rajout de l'adresse MAC de interface Ethernet (cuivre) que vous souhaitez exclure
 _[Keyfile]
Unmanaged-device=mac :xx :xx :xx :xx :xx :xx_


Arrêt de l'interface WLAN
 _ifconfig wlan0 down_

Passage de l'interface wlan0 en mode moniteur
 _iwconfig wlan0 mode monitor_

Redémarrage de l'interface WLAN
 _ifconfig wlan0 up_

C'est moins brutal..

Comme cela, il est possible de se connecter sur le Raspberry à distance durant le test pour recevoir les trames.

Bons tests

**Comment by PercyMgn** [comment]
Merci les informations.
Je ferme la discussion.
Bonne soirée
