### ISSUE TITLE
Erreur lors de l'execution du code sur laptop

### ISSUE THREAD

**Issue by gharbit** [GendarmerieNationale/ReceptionInfoDrone#7]
Bonjour,

En lançant le script (nom de l'interface mis à jour dans main.py, pas de dépendance python-scapy installée sur la machine), j'obtiens l'erreur suivante:
`root@tghvm:/home/tgh/Workspace/ReceptionInfoDrone# python3 main.py 
Lancement du script.
Lancement du mode monitor.
Mode monitor de l'interface wlxd0374599b9ea
Process sniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tgh/Workspace/ReceptionInfoDrone/lib/sniff.py", line 61, in sniffer
    prn=lambda trameBeacon: put_in_queue_beacon(queue_beacon, trameBeacon), count=0, store=False)
  File "/home/tgh/Workspace/ReceptionInfoDrone/lib/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/home/tgh/Workspace/ReceptionInfoDrone/lib/scapy/arch/linux.py", line 458, in __init__
    _flush_fd(self.ins)
  File "/home/tgh/Workspace/ReceptionInfoDrone/lib/scapy/arch/linux.py", line 381, in _flush_fd
    os.read(fd, MTU)
OSError: [Errno 100] Network is down
`

Avez-vous une idée sur l'origine de l'erreur?

Ma configuration logicielle est la suivante:
- Laptop tournant Ubuntu 18.04 + kernel 5.0.0-32-generic.
- Aircrack 1.2
- Python 3.6.8

Ma configuration matérielle est:
- Adaptateur USB Wifi TP-Link TL-WN722N (version 1)
https://www.materiel.net/produit/201203160105.html?gclid=Cj0KCQiA3NX_BRDQARIsALA3fIKZCPmH2_z4uDHjUXYL0O6E1dQpskHeIqSPjMTZGTLUVKHWNnw0afYaAnfeEALw_wcB#a_aid=5ba117fe4c3bc&data1=shopping-reseau
- Balise d'identification Beacon
https://www.studiosport.fr/balise-didentification-electronique-a-distance-zephyr-beacon-light-dronavia-a19966.html

Bien à vous. Merci
Cordialement,

**Comment by PercyMgn** [comment]
Bonjour,

Voici ce que vous pouvez exécuter comme commande pour vérifier si votre chispet wifi passe correctement en mode monitor avec airmon :
- sudo airmon-ng start wlxd0374599b9ea
- ip a (cela vous permet de vérifier si airmon rajoute "mon" à la fin du nom de votre interface wifi)
- sudo airodump-ng wlxd0374599b9ea(avec ou sans "mon" à la fin en fonction du résultat de ip a)

Laissez tourner airodump quelques secondes/minutes afin de vérifier si vous recevez bien des trames wifi.

Merci de me faire un retour sur l'exécution des ces commandes.

Bonne journée

**Comment by gharbit** [comment]
Bonjour, 
Finalement, le chip ne peut pas passer en mode monitoring. Une erreur est générée. 

Cordialement,

**Comment by PercyMgn** [comment]
Oui, c'est bien ce que je pensais. 
Le problème vient donc du chipset wifi.
Cordialement,
