### ISSUE TITLE
Problème mise en place système

### ISSUE THREAD

**Issue by TWAB** [GendarmerieNationale/ReceptionInfoDrone#8]
Bonjour, j'essaye de mettre en place le système et je rencontre un problème.
Je n'ai pas exactement les mêmes dépendances je sais pas si ca pose problème ?

Raspberry pi 4, python 3.7.3, Wifi : Alfa network awus036acs, OS : Raspbian GNU/Linux 10 (buster)

J'ai l'impression que mon problème viens du fait que ma clé wifi n'est pas reconnu ou bien paramétrée.
Voici ce que j'obtiens au lancement du script 

sudo python3 main.py

Lancement du script.
Lancement du mode monitor.
Mode monitor de l'interface wlx00c0ca907956-network
Process sniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Transpondeur/lib/sniff.py", line 61, in sniffer
    prn=lambda trameBeacon: put_in_queue_beacon(queue_beacon, trameBeacon), count=0, store=False)
  File "/home/pi/Transpondeur/lib/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 456, in __init__
    set_promisc(self.ins, self.iface)
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 145, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/home/pi/Transpondeur/lib/scapy/arch/common.py", line 50, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
Exception ignored in: <function SuperSocket.__del__ at 0xb60aa6f0>
Traceback (most recent call last):
  File "/home/pi/Transpondeur/lib/scapy/supersocket.py", line 123, in __del__
    self.close()
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 145, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/home/pi/Transpondeur/lib/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/home/pi/Transpondeur/lib/scapy/arch/common.py", line 50, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device

Arret du script.

Merci, bien à vous

Baptiste

**Comment by PercyMgn** [comment]
Bonjour,

Il y a peut-être un problème concernant votre chipset wifi en effet.

Avant de lancer le script, il faut s'assurer que vous pouvez passer votre wifi en mode monitor avec airmon-ng grâce aux commande suivante :
- sudo airmon-ng start votreInterfaceWifi
- ip a (cela vous permet de vérifier si airmon rajoute "mon" à la fin du nom de votre interface wifi)
- sudo airodump-ng votreInterfaceWifi(avec ou sans "mon" à la fin en fonction du résultat de ip a)

Laissez tourner airodump quelques secondes/minutes afin de vérifier si vous recevez bien des trames wifi.

Bonne journée

**Comment by TWAB** [comment]
Merci pour les informations, je suis passé par Kali pour m'affranchir d'une antenne externe, je n'arrivais pas à paramétrer mon antenne externe. Ca marche bien la avec vos manip, je m'en contenterai.
Merci
Bonne journée

**Comment by TWAB** [comment]
Merci, j'ai réussi à paramétrer mon antenne correctement puis en faisant vos manip (avec un airmon-ng check kill), j'obtiens une trame.
Je reçois juste JSON du drone : {"92": ""}
J'ai fait la manip du print("Trame brut : ", trame) pour avoir la trame complète, je reçois pleins de chose en Hexa, avec juste mon identifiant unique que j'arrive à identifier.
Est-ce normal que dans le message JSON du Drone je n'ai rien ?
Et ma trame obtenue avec le print avec pleins de x00\xff\x02 ... est normal aussi ?

Merci

**Comment by PercyMgn** [comment]
Bonjour,
Oui la trame brut est en hexa.
C'est pour cela qu'on a besoin de la décoder. 
Une fois décodée, on obtient un json avec les différents points de l'arrêté.
Si vous n'obtenez pas le bon json c'est que votre trame n'est pas bien formée.
D'où vient votre trame ? 
Qui la génère ?

**Comment by TWAB** [comment]
Je possède une balise Beacon Light de la société DRONAVIA, je ne fait rien de plus que de venir alimenter l'appareil et écouter ce qu'il émet. Une fois qu'il a trouvé sa position GPS (témoin lumineux) je reçois bien des trames, avec notamment son numéro d'identification mais par contre mon JSON et vide.

**Comment by PercyMgn** [comment]
Vous devriez vous rapprocher du fabricant.
Le fabricant pourra, s'il le souhaite, prendre contact directement avec nous afin que nous l'aidions si jamais le problème vient de chez lui.
Il doit y avoir un problème avec leur trame.
Le code suit l'arrêté et a été utilisé pour décoder les trames de Dji, Parrot et d'autres entreprises. Il a, jusque là, toujours fonctionné pour décoder les trames.
Je ferme ici. Ouvrez un nouveau problème si besoin.

**Comment by TWAB** [comment]
D'accord merci pour tout

**Comment by PercyMgn** [comment]
Par curiosité, je veux bien la trame brut que vous recevez sur votre écran.
Merci

**Comment by TWAB** [comment]
J'ai rechargé le programme à partir de 0 et j'obtiens ca maintenant : 
JSON du drone :  {"92":"","201":1602799346,"202":1602799346,"203":6,"204":-90}
JSON du drone :  {"92":"","201":1602799349,"202":1602799349,"203":6,"204":-88}
JSON du drone :  {"92":"","201":1602799363,"202":1602799363,"203":6,"204":-92}
JSON du drone :  {"92":"","201":1602799368,"202":1602799368,"203":6,"204":-90}
JSON du drone :  {"92":"","201":1602799371,"202":1602799371,"203":6,"204":-90}

Mieux mais pas vraiment encore ce que je veux

**Comment by TWAB** [comment]
Et avec la trame brut

JSON du drone :  {"92":"","201":1602799861,"202":1602799861,"203":6,"204":-88}
Trame brut :  b'\x00\x00\x1a\x00\xae@\x00\xa0 \x08\x00\x00\x10\x02\x85\t\xa0\x00\xa8\x00T\x00\x00\x00\x00\x00\x80\x00\x00\x00\xff\xff\xff\xff\xff\xffY4Q5H8Y4Q5H8\xb0\x15\x00\x00\x00\x00\x00\x00\x00\x00\xf0\n\x00\x00\x00\x00\x01\x08\x82\x84\x8b\x96$0Hl\x03\x01\x06\xddNj\\5\x01\x01\x01\x01\x02\x1e[il y avait ne num de mon appareil]\x04\x04\x00E\xe8\xa7\x05\x04\x00\x07B\x97\x06\x02\x01J\x07\x02\xff\x94\x08\x04\x00E\xe8\x95\t\x04\x00\x07B;\n\x01\x00\x0b\x02\x01\x01\xc4\x1c^\xed'

**Comment by TWAB** [comment]
C'est bon, j'ai réussi à retrouver une trame correct, pour mieux comprendre le problème j'ai print la liste data qui contient les trames. J'ai eu :
Data =  b'\\5\x01\x01\x01\x01\x02\x1e(N° de mon appareil)\x04\x04\x00E\xe8\xa7\x05\x04\x00\x07B\x9e\x06\x02\x01C\x07\x02\xff\x8d\x08\x04\x00E\xe8\x95\t\x04\x00\x07B;\n\x01\x00\x0b\x02\x01\x01'

et j'ai constaté que au moment ou le programme fait t=ord(data[0:1]) t prenait la valeur de 92 donc de "\\" et v de 53 donc de "5"
Le problème était donc que les premiers éléments de ma liste étaient \\5, j'ai donc rajouté juste après la déclaration de data un : 
data = data[3:] pour enlever les premières valeurs.
Et c'est bon ma trame était correct.

Merci pour l'aide et la réactivité.
