### ISSUE TITLE
Type de modulation

### ISSUE THREAD

**Issue by AMCPV** [GendarmerieNationale/ReceptionInfoDrone#9]
Bonjour,

ReceptionInfoDrone semble ne faire aucun contrôle du type de modulation utilisé ni de la largeur de canal. 
Or le texte précise que la modulation doit être OFDM et que la largeur de canal doit être de 20MHz ou moins.
Est il prévu d'ajouter ces informations pour obtenir une validation strict du signal émis en plus de la validation de la trame.

Cordialement.

**Comment by PercyMgn** [comment]
Bonjour,

Ce petit bout de code a pour but uniquement d'afficher la trame selon l'arrêté.
Il n'a pas vocation à vérifier la bonne conformité de la transmission mais juste le payload.
Merci.
Cordialement,

**Comment by AMCPV** [comment]
Je vous remercie.
Cordialement
